version: '3'
services:
    node:
        image: 'node:latest'
        volumes:
            - './:/home/node/app'
        working_dir: /home/node/app
        ports:
            - '3000:3000'
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm start'